"""Baseline: reconcile any real database with the current schema.

Revision ID: 0001
Revises:
Create Date: 2026-08-13

Every schema change before this project had live migration tooling landed
as a direct edit to models.py (#229) -- there is no recorded history of
what any given deployed `~/.rivulets/rivulets.db` actually looks like, only
what today's `Base.metadata` says it *should* look like. A conventional
autogenerated baseline (a frozen list of `op.create_table` calls, replayed
top to bottom) can't handle that: it assumes the target database is either
fully empty or already at some known prior revision, and a workspace that
picked up 0.3, then 0.4-dev, then today's `main` in some partial order is
neither.

So this revision is deliberately not a frozen DDL snapshot. It inspects
whatever tables/columns/indexes already exist and creates only what's
missing to reach the current `Base.metadata` -- a no-op replay of
`create_all` for a brand new workspace, and a real `ALTER TABLE` catch-up
for an old one, via the same code path. This is a one-time exception: every
revision after this one is a normal autogenerated, frozen-DDL migration,
because from here on `alembic_version` gives us real prior-state to diff
against.

Known limitations, both about columns added to a table that already
existed: only handles the column shapes this schema has actually used so
far -- nullable columns, and NOT NULL columns with a simple scalar
`mapped_column(default=...)` (bool/int/float/str) SQLAlchemy applies
client-side on INSERT. SQLite requires a literal DEFAULT in the ALTER
statement itself to backfill existing rows for a NOT NULL column with none
of those, and this project's models have never used `server_default`, so
there's no DDL-level default to fall back to -- see `_sqlite_literal_default`
below; a future column that needs something else (a callable default, a
CHECK constraint) needs its own hand-written migration, and this baseline
raises loudly rather than silently producing a broken column. Also, a
`ForeignKey` on a newly-added column isn't reconstructed as a DDL
constraint (SQLite ADD COLUMN can't add one to a non-empty table without a
full table rebuild) -- the column round-trips fine, it just isn't
FK-enforced until a hand-written migration rebuilds the table.
"""

from __future__ import annotations

from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.schema import ColumnDefault

from rivulets.db.base import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def _sqlite_literal_default(column: sa.Column[Any]) -> str | None:
    """A SQL literal for an ALTER TABLE ... ADD COLUMN DEFAULT clause, or
    None if the column doesn't need one (nullable) or none can be derived
    from its Python-side `mapped_column(default=...)`."""
    if column.nullable:
        return None
    default = column.default
    if not isinstance(default, ColumnDefault) or not default.is_scalar:
        return None
    value = default.arg
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return None


def _add_missing_column(
    bind: sa.engine.Connection, table_name: str, column: sa.Column[Any]
) -> None:
    compiled_type = column.type.compile(dialect=bind.dialect)
    ddl = f'ALTER TABLE "{table_name}" ADD COLUMN "{column.name}" {compiled_type}'
    if not column.nullable:
        default_literal = _sqlite_literal_default(column)
        if default_literal is None:
            raise RuntimeError(
                f"Cannot add NOT NULL column {table_name}.{column.name} during migration: "
                "no literal default available for the SQLite backfill. Give it a plain "
                "scalar mapped_column(default=...), make it nullable, or write a "
                "hand-authored migration for this column."
            )
        ddl += f" NOT NULL DEFAULT {default_literal}"
    op.execute(ddl)


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    for table in Base.metadata.sorted_tables:
        if table.name not in existing_tables:
            table.create(bind=bind, checkfirst=True)
            continue

        existing_columns = {col["name"] for col in inspector.get_columns(table.name)}
        for column in table.columns:
            if column.name not in existing_columns:
                _add_missing_column(bind, table.name, column)

        existing_indexes = {idx["name"] for idx in inspector.get_indexes(table.name)}
        for index in table.indexes:
            if index.name not in existing_indexes:
                index.create(bind=bind, checkfirst=True)


def downgrade() -> None:
    raise NotImplementedError(
        "Baseline revision reconciles whatever already existed with the current schema "
        "rather than creating a fixed set from nothing -- there's no well-defined "
        "'previous state' to downgrade to."
    )
