"""Add sync_pending_outbound.deleted (#238)

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-13

Distinguishes a queued live-state publish from a queued tombstone publish
-- see db/models.py's SyncPendingOutbound docstring and sync/publish.py's
`_record_pending_outbound`. Hand-written rather than autogenerated: 0001
(baseline) reconciles against `Base.metadata` dynamically at run time
(its own docstring), so a dev DB migrated after this column was already
added to models.py would show no diff for autogenerate to find -- this is
the normal, frozen-DDL kind of revision 0001's docstring says everything
after it should be.

Guarded with an existence check for the same reason: 0001's dynamic
reconciliation means a brand-new workspace running the *whole* chain in
one go (0001 then this) already has the column by the time this revision
runs -- 0001 read today's `Base.metadata`, which already includes it.
Only a workspace that was already sitting at 0001 (this column genuinely
missing) needs this migration to do real work.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "sync_pending_outbound"
_COLUMN = "deleted"


def _has_column() -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return _COLUMN in {col["name"] for col in inspector.get_columns(_TABLE)}


def upgrade() -> None:
    if _has_column():
        return
    with op.batch_alter_table(_TABLE) as batch_op:
        batch_op.add_column(
            sa.Column(_COLUMN, sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    if not _has_column():
        return
    with op.batch_alter_table(_TABLE) as batch_op:
        batch_op.drop_column(_COLUMN)
