"""Make agent_run.agent_id nullable (#246)

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-13

llm_fallback.py's dispatcher-side routing call (#246) now writes its own
AgentRun row (source='dispatcher_call') so its spend stops being invisible
to the usage dashboard and budget caps. That call runs before any single
agent has been matched -- it evaluates a whole team's roster at once -- so
there's no agent_id to attach it to. Every other AgentRun keeps a real
agent_id; see db/models.py's AgentRun docstring for the full reasoning.

Hand-written rather than autogenerated, same reasoning as 0002: 0001's
dynamic reconciliation against today's Base.metadata means a brand-new
workspace never needs this migration to do real work, only one already
sitting at an earlier revision with the column still NOT NULL.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "agent_run"
_COLUMN = "agent_id"


def _is_nullable() -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for col in inspector.get_columns(_TABLE):
        if col["name"] == _COLUMN:
            return bool(col["nullable"])
    return True  # column missing entirely -- nothing for this revision to do


def upgrade() -> None:
    if _is_nullable():
        return
    with op.batch_alter_table(_TABLE) as batch_op:
        batch_op.alter_column(_COLUMN, existing_type=sa.String(), nullable=True)


def downgrade() -> None:
    if not _is_nullable():
        return
    with op.batch_alter_table(_TABLE) as batch_op:
        batch_op.alter_column(_COLUMN, existing_type=sa.String(), nullable=False)
