"""Add unique partial index on tool.name for tool_type='custom' (#289)

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-14

`Tool.name` had no unique constraint, so a peer could sync in a custom
tool with a different id but the same name as one already assigned
locally -- both api/tools.py's create_tool and sync/apply.py's
apply_remote_tool_change wrote `{name}.py`, so whichever write landed
last silently overwrote the source a victim's agent was already invoking
under an unrelated, already-approved assignment. See db/models.py's Tool
docstring on `idx_tool_custom_name` for the full reasoning, including why
this is scoped to `tool_type='custom'` rather than every tool.

Hand-written rather than autogenerated, same reasoning as 0002/0003/0004:
0001's dynamic reconciliation against today's Base.metadata means a
brand-new workspace never needs this migration to do real work, only one
already sitting at an earlier revision without the index.

If an existing workspace already has two 'custom' tools sharing a name
(the exact bug this closes), this migration's CREATE UNIQUE INDEX fails
loudly rather than silently picking a winner -- the same "raise rather
than guess" treatment 0001's docstring gives an unhandled column shape.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "tool"
_INDEX = "idx_tool_custom_name"


def _has_index() -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return _INDEX in {idx["name"] for idx in inspector.get_indexes(_TABLE)}


def upgrade() -> None:
    if _has_index():
        return
    op.execute(
        f'CREATE UNIQUE INDEX "{_INDEX}" ON "{_TABLE}" ("name") WHERE tool_type = \'custom\''
    )


def downgrade() -> None:
    if not _has_index():
        return
    op.execute(f'DROP INDEX "{_INDEX}"')
